name: Deploy CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install Deps
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Inicializando NPM
        run: npm init -y

      - name: Baixando as dependencias
        run: npm install jest

      - name: Code testing
        run: npm test myApp.js
