name: Deploy CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building App
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

#      - name: Code testing
#        run: npm run test

      - name: Build application
        run: npm run build
  
