name: Deploy CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building App
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Installing dependencies
        run: npm install express puppeteer

      - name: Code testing
        run: npm test src/myApp.js
  
