name: Deploy CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install Deps
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

#      - name: 